The-OpenROAD-Project/bazel-orfs

MODULE.bazel, README.md, WORKSPACE, openroad.bzl
This PR fixes issues with escaping environment variables with spaces, e.g. `"DIE_AREA=0 0 400 400"`.
The most important change here is the transition from the usage of `run_binary()` rule from [Aspect Bazel Lib](https://github.com/aspect-build/bazel-lib) to simple native [genrules](https://bazel.build/reference/be/general#genrule). This change was required because of a bug in the implementation of `run_binary()` rule in `Aspect Bazel Lib` (see https://github.com/aspect-build/bazel-lib/issues/666). The implementation from [Bazel Skylib](https://github.com/bazelbuild/bazel-skylib) is also prone to this bug and additionally has problems with expanding `RULEDIR` built-in make variable (see https://github.com/bazelbuild/bazel-skylib/issues/438).
Additionally, a slightly modified version of …
=> Fix wrapping env vars

README.md, openroad.bzl
We don't want to depend on the previous stages because that forces rebuilds that are potentially unnecessary. It should be possible to use old artifact, generate the script and continue the flow with it.
CC @oharboe
=> _make targets: do not depend on previous stages

README.md, openroad.bzl
This PR is a continuation of https://github.com/The-OpenROAD-Project/bazel-orfs/pull/5.
It breaks the dependency chain for `_make` script targets. We don't want to build all dependencies required for **running** the script. It is only required to build dependencies for **building** the script itself. It is up to the user to provide all the requirements for running the script.
Building dependencies for running `_make` script should be done separately with e.g.:
```
bazel build $(bazel query "deps(stage_target) except <stage_target>")
```
CC @oharboe, @nekronos
=> Break dependency chain for _make script generation

README.md, openroad.bzl
This PR modifies `_make` genrules so that generated shell script will set write permissions in cwd (which is expected to be `bazel-bin`). This allows removing additional manual step o changing permissions between generating the script and running it.
=> Include chmod in _make scripts

BUILD, README.md, config.mk, entrypoint.mk, openroad.bzl, orfs
This PR modifies the build rules to not depend on `entrypoint` attribute. It also removes `BAZEL_ORFS` environment variable as it is no longer required. A new environment variable `MAKE_PATTERN` is introduced to keep path to `*.mk` file relevant to given stage of ORFS flow.
It also includes a small cleanup with regards to loops used in the macro definition.
In subsequent PR the `entrypoint` attribute will be removed from the repository entirely. This will be done after https://github.com/The-OpenROAD-Project/megaboom/pull/25 is merged.
=> Stop using entrypoint attribute

openroad.bzl
This PR add some docstrings to `openroad.bzl` which document the functions and macro definition.
=> openroad.bzl: Add docstrings

BUILD, openroad.bzl
This PR fixes issues with wrapping into quotes environment variables with spaces in their values when using `_make` targets.
The first commit adds additional argument for the example `floorplan` stage which have spaces in its value (`MACRO_PLACE_HALO=10 10`).
When using `_make` targets this env var was not quoted appropriately which caused make to interpret second part of this value as target name resulting in errors such as those (see [this](https://github.com/antmicro/bazel-orfs/actions/runs/8324089522/job/22774960281#step:10:41) CI run)
```
make: *** No rule to make target '10'.  Stop.
```
The fix modifies the `wrap_args()` helper function to include additional escaping sequences for the single quotes in order to preserve those when building shell scripts for running `_make` targets. …
=> Fix env var wrapping

.github/workflows/ci.yml
This is a small improvement to the CI.
This PR adds an additional job which installs [buildifier](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md) tool and uses it to check the formatting of bazel files. It is a nice and easy way to keep all build files formatted in a standard way.
=> CI: Add lint check

.bazelrc
This PR adds `.bazelrc` configuration file with an option that prevents bazel from inheriting environment variables from the environment of the `bazel` caller.
This fixes cache invalidation when environment variable like e.g. `PATH` changes.
CC @oharboe
=> Do not inherit env vars from the caller environment

openroad.bzl
Ideally we provide only the variables relevant for a stage to that stage. Is ADDITIONAL_LIBS relevant, other than for `make cts_issue`?
What about ADDITIONAL_LEFS?
This is not strictly necessary for the execution of this stage, but it is useful, otherwise .lib files for macros are not included in make cts_issue.
=> cts: include ADDITIONAL_LIBS in variables to CTS stage

openroad.bzl
Running generated scripts on `zsh` results in fail without any error message. This PR fixes it by using bash for running scripts.
=> Fix scripts for Z shell

openroad.bzl, orfs
@oharboe  this should fix the local flow.
This PR additionally adds the `docker_image` attribute to `build_openroad` macro which allows specifying docker image for given build. Please note that you may experience permission errors when building one part of the design with one docker image, and second part with other image.
=> Fix local flow in external repos

docker_shell.sh, openroad.bzl, orfs
This PR addresses the permission issues, which results in failing with `Permission error` or getting stuck with `[...] overriding mode 0555 (r-xr-xr-x)?`. It makes sure that files in workspace (`bazel-bin` directory) are writable and can be overridden.
=> Fix permission denied errors

.github/workflows/ci.yml, BUILD, MODULE.bazel, MODULE.bazel.lock, openroad.bzl
This PR supersedes https://github.com/The-OpenROAD-Project/bazel-orfs/pull/22.
CC @oharboe
=> Use default name for the ORFS docker image

README.md
Here are some initial updates to the README. Some of the changes describe modifications that will come in follow-up PRs with regards to handling of docker images. Please let us know if there are some additional topics that you would want to have included in this README.
There will be also an update to the megaboom README (e.g. pointing to bazel-orfs README for initial setup and usage guide)
CC @oharboe
=> README: update instructions and usage guide

docker_shell.sh, openroad.bzl
Currently, when CTRL-C is used, Bazel sends `SIGKILL` to subprocesses, which only kills script process, but not Docker container.
This PR fixes this behavior, by enabling `graceful-termination` and handling `SIGTERM` signal.
=> Stop containers on interrupts

make_script.template.sh, openroad.bzl
This PR breaks generated _make scripts into multiple lines. Example for `L1MetadataArray_test_floorplan_make`:
```bash
#!/bin/bash
set -uo pipefail
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
source "$0.runfiles/$f" 2>/dev/null ||
source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
{
echo>&2 "ERROR: cannot find $f"
exit 1
}
f=
set -e
DESIGN_CONFIG=$(rlocation _main/L1MetadataArray_test_config.mk) \
STAGE_CONFIG=$(rlocation _main/L1MetadataArray_test_floorplan_config.mk) \
MAKE_PATTERN=$(rlocation …
```
=> Format generated _make script

make_script.template.sh
Point out that this is a boilerplate code of `Bazel Bash runfiles library` and refer to the `README` which describes this in detail.
=> make_script.template.sh: Add comment about Bash runfiles library boilerplate code

README.md
=> README: use anchored links

BUILD, test/mock/tag_array_64x184.sv
Fixes upcoming error when upgrading ORFS:
```
$ bazel build tag_array_64x184_generate_abstract
[deleted]
ERROR: TCL interpreter returned an error: 
Rows            | Width           | Total bits      | Name                                              
---------------------------------------------------------------------------------------------------------
64              | 184             | 11776           | tag_array_64x184.Memory                           
ERROR: Synthesized memory size exceeds maximum allowed bits 4096
[deleted]
```
Also, speeds up running times.
Running times after:
```
Log                            Elapsed seconds Peak Memory/MB
1_1_yosys                                   10            149
2_1_floorplan                                4            241 …
```
=> tests: speed up by mocking 128 row SRAM with 16 rows

BUILD, openroad.bzl
@eszpotanski @lpawelcz Thoughts?
=> dry: add add_option_all_stages() helper function

.github/scripts/build_local_target.sh, .github/workflows/ci.yml, README.md, docker_shell.sh, openroad.bzl
This PR adds `_scripts` target, which generates two scripts, for local flow (using `orfs`) and Docker flow (using `docker_shell.sh`).
To follow https://github.com/The-OpenROAD-Project/bazel-orfs/pull/27#issuecomment-2069770213, scripts are generated with `_scripts` target, and `_make` targets depends on `_scripts` apart from building all required dependencies for the stage.
Moreover, `docker_shell` can detect whether bazel-orfs directory has to be mounted and automatically adds necessary argument to `docker run`. Therefore, no additional changes will be required, when bazel-orfs is used with `local_path_override`.
=> Generate scripts for local and Docker flow

openroad.bzl
This PR changes order of displayed targets, so that generated scripts are printed at the end.
Before:
```
Target //:tag_array_64x184_floorplan_make up-to-date:
bazel-bin/logs/asap7/tag_array_64x184/base/make_script_floorplan.sh
bazel-bin/tag_array_64x184_floorplan_local_make
bazel-bin/logs/asap7/tag_array_64x184/base/make_docker_script_floorplan.sh
bazel-bin/tag_array_64x184_floorplan_docker
bazel-bin/results/asap7/tag_array_64x184/base/1_synth.v
bazel-bin/logs/asap7/tag_array_64x184/base/1_1_yosys.log
bazel-bin/logs/asap7/tag_array_64x184/base/1_1_yosys_hier_report.log
```
```
INFO: Analyzed target //:tag_array_64x184_floorplan_scripts (1 packages loaded, 21 targets configured).
Target //:tag_array_64x184_floorplan_scripts up-to-date: …
```
=> Change order in which targets are displayed at the end of the build

.github/scripts/build_local_target.sh, .github/workflows/ci.yml, BUILD, README.md, docker_shell.sh, openroad.bzl
This PR adds `*_gui` targets for Docker flow, which has to be called with `run`, e.g.:
```
bazel run L1MetadataArray_full_final_gui
```
GUI for local flow works fine, apart from synthesis stage, which requires additional LEF files - new target `*_gui_synth_make` resolves this issue.
=> Add targets running OpenROAD GUI with Docker image

docker_shell.sh, openroad.bzl, orfs
This PR adds optional `debug_prints` attribute to the `build_openroad()` macro. It enables shell command traces and echoes from `make`. It is disabled by default.
=> build_openroad: Introduce debug_prints attribute

README.md, test/constraints-sram.sdc, test/io-sram.tcl, test/io.tcl
relative paths work.
@eszpotanski @lpawelcz I want to reduce the number of surprises and differences between using ORFS standalone and using bazel-orfs.
=> orfs: fewer surprises now that cwd is in the build folder

.github/workflows/ci.yml, BUILD, README.md, openroad.bzl, subpackage/BUILD, subpackage/rtl/tag_array_64x184.sv
Trying to call `build_openroad()` from subpackages does not currently work. I've drafted a sketch to make it work when called from subpackages of `bazel-orfs`.
It still does not work when `build_openroad()` is called from a subpackage in an external project, with the following error message from `docker_shell.sh`, I believe it has to do with how `WORKSPACE_ROOT` is defined.
```
+ chmod -R +w /home/.../execroot/_main/execroot/_main/bazel-out/k8-fastbuild/bin
chmod: cannot access '/home/.../execroot/_main/execroot/_main/bazel-out/k8-fastbuild/bin
```
=> Subpackage targets

docker_shell.sh, openroad.bzl
In order to interpret `.tcl` scripts using `./bazel-bin/Top_variant_floorplan_docker open_floorplan < script.tcl`, `docker_shell` must pass `stdin` to `make`. If there are less ill-advised ways to achieve this, any help would be appreciated.
@oharboe
=> Docker flow: Forward `stdin`

openroad.bzl
When doing `bazel build '...'` I get:
```
//subpackage:tag_array_64x184_synth_sdc_make: missing input file '//subpackage:out'
```
```
$ bazel cquery 'somepath(//subpackage:tag_array_64x184_clock_period_make, //subpackage:out)'
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets...
//subpackage:tag_array_64x184_clock_period_make (6220210)
//subpackage:tag_array_64x184_clock_period_scripts (6220210)
//subpackage:out (null)
```
reveals the offending dependency path.
I made an initial suggestion on how to fix this, that assumes `create_out_rule()` is instantiated on the `WORKSPACE` level. ~On closer thought, however, I wonder why `//...:..._scripts` should depend on `//:out` at all?~ Nevermind, found …
=> openroad: Fix `out` label

BUILD, MODULE.bazel, MODULE.bazel.lock, README.md, external_pdk/external_pdk.patch, openroad.bzl
This PR modifies bazel macros to add support for running physical design flows with external PDKs provided in the format accepted by ORFS (for more information please refer to: https://openroad-flow-scripts.readthedocs.io/en/latest/contrib/PlatformBringUp.html#platform-configuration).
PR adds new `external_pdk` attribute to the `build_openroad()` macro. This attribute points to bazel external dependency with the unpacked PDK archive. The directory of this PDK is then set as the value of `PLATFORM_HOME` env var and the name of the PDK is set as `PLATFORM` env var. When ORFS flow is launched, those env vars are used to construct the `PLATFORM_DIR` env var which points ORFS tools to the directory of the external PDK.
Two example build configurations were added for testing purposes.
> …
=> Add suport for external PDKs

BUILD, README.md, openroad.bzl
This PR introduces a few changes required for remote execution, like:
* adding `:remote_exec` config,
* moving constraints' dependencies to sources (otherwise they are not available during remote execution),
* running Stage targets with local flow for remote execution.
=> Introduce changes for remote execution

docker_shell.sh
This PR fixes warning about not existing file by creating it.
=> Fix `xauth: file does not exist` warning 

openroad.bzl
This PR prevents from building Scripts targets remotely to make sure created scripts are fitted to run locally.
=> openroad: Do not build scripts remotely

openroad.bzl
This PR adds missing `_` in dependency name.
=> openroad: Fix typo in GUI dependency

openroad.bzl
This allows `$(location <label>)` expansion in user provided arguments.
=> openroad: Pass user provided `stage_sources` to configuration targets

BUILD, docker_shell, openroad.bzl
This PR changes how `docker_shell` is used - instead of wrapping it with `sh_binary`, it used directly. This should make the cache hits more robust.
=> Use `docker_shell` directly

docker.BUILD.bazel, patcher.py
This prevents the binaries from having different
`.interp` sections depending on where the binary
is patched.
The method of finding `execution_root` makes the
dangerous assumption that it is two directories
up from the repository directory.
=> patcher.py: Set interpreter using relative path

BUILD, openroad.bzl
This requires creating an empty file when reports are disabled because bazel does not have conditional outputs
=> orfs_flow: test SKIP_REPORT_METRICS=1

openroad.bzl
This PR addresses the unnecessary copying of source files to the output directory in the `openroad.bzl` script.
Before modifications:
```
$ bazel run L1MetadataArray_place -- `pwd`/build
$ find build/ | grep -v external | grep floorplan
build/results/asap7/L1MetadataArray/base/2_floorplan.odb
build/results/asap7/L1MetadataArray/base/2_floorplan.sdc
```
After:
```
$ bazel run L1MetadataArray_place -- `pwd`/build
$ find build/ | grep -v external | grep floorplan
```
This PR modifies the following:
* `openroad.bzl`
* Modified the `GENFILES` substitution to exclude `ctx.files.src`, ensuring that source files are not copied to the output directory.
* Updated the runfiles section to exclude `ctx.files.src`, aligning it with the updated `GENFILES` logic.
=>  Avoid copying source files to the output

MODULE.bazel, MODULE.bazel.lock, docker.bzl, extension.bzl, patcher.py
This PR changes how the `@docker_orfs` is created to speed up the process of changing the ORFS version.
First of all, instead of exporting Docker image to TAR file and extracting it, Docker container is run and files are copied directly from it.
Moreover, `patcher.py` script was parallelized - read-only commands are run in parallel preparing `patchelf` commands updating linking information, which are later on run sequentially.
When updating ORFS version from `v3.0-1114-g46acc762` to `v3.0-1154-gdfcf7c64`, following speedup can be observed:
* without cached image - decrease from 4m to 2m45s,
* with cached image - decrease from 2m30s to 1m30s.
=> Speed up ORFS version change

BUILD, openroad.bzl
This PR introduces LoggingInfo provider, which passes current and previous logs and reports. In addition to that, it includes logs and reports in the build directory, e.g. for command:
```
bazel run //:L1MetadataArray_cts -- `pwd`/build
```
It includes all logs and reports up to built target.
=> Added including logs and reports in the `bazel run` output directory

BUILD, MODULE.bazel, docker.BUILD.bazel, eqy.bzl, eqy.tpl, oss_cad_suite.BUILD.bazel, test/rtl/Mul.sv
@hovind FYI
```
$ bazel run Mul_synth_eqy
INFO: Analyzed target //:Mul_synth_eqy (0 packages loaded, 0 targets configured).
Target //:Mul_synth_eqy up-to-date:
bazel-bin/Mul_synth_eqy.run.sh
INFO: Elapsed time: 0.213s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh ./Mul_synth_eqy.run.sh
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:Mul_synth_eqy
-----------------------------------------------------------------------------
EQY 15:47:26 [Mul_synth_eqy] read_gold: starting process "yosys -ql Mul_synth_eqy/gold.log Mul_synth_eqy/gold.ys"
EQY 15:47:26 [Mul_synth_eqy] read_gold: finished (returncode=0)
EQY 15:47:26 …
```
=> eqy: Add `eqy_test` rule for equivalence checking and test

BUILD, README.md, openroad.bzl, subpackage/BUILD
This PR introduces `grt` as a separate stage from `route`.
Now, stages may have multiple source stages instead of only one. This was needed, as the new `route` stage needs both `congestion.rpt` file, which comes from the `grt` route, and `4_cts.sdc` file, which is produced by a `cts` stage. 
Attaching `before` and `after` outputs produced by:
`bazel query "deps(//:L1MetadataArray_generate_abstract)" --output=graph --noimplicit_deps --notool_deps > graph && xdot graph`
=> Make GRT a separate step

deploy.tpl, openroad.bzl
yosys-dependencies is now run during bazel run so that e.g. make memory does not first spit out lots of surprising output
=> bazel run: synth/canonicalize nit

docker.BUILD.bazel, openroad.bzl
This PR addresses issues regarding missing definitions for `QT_QPA_PLATFORM_PATH` in the environment and a malformed link to `libstdbuf.so` in `klayout`.
The error logs for those problems:
```
[WARNING GUI-0076] Could not find the Qt platform plugin "offscreen" in ""
```
```
external/bazel-orfs~~orfs_repositories~docker_orfs/usr/bin/klayout: /home/jbylicki/.cache/bazel/_bazel_jbylicki/1cb0e4ab858bdcd626912cbee0441148/external/bazel-orfs~~orfs_repositories~docker_orfs/usr/bin/../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /usr/lib/coreutils/libstdbuf.so)
external/bazel-orfs~~orfs_repositories~docker_orfs/usr/bin/klayout: /home/jbylicki/.cache/bazel/_bazel_jbylicki/1cb0e4ab858bdcd626912cbee0441148/external/bazel-orfs~~orfs_repositories~docker_orfs/usr/b …
```
=> Fixed _make_impl environment variable configuration

docker.BUILD.bazel, openroad.bzl
This is a follow-up to the merged draft PR https://github.com/The-OpenROAD-Project/bazel-orfs/pull/131 that fixes the issues regarding `QT_QPA_PLATFORM_PATH`. It adds `qt_plugins` dependency and fixes the path to the library (uses `commonpath(ctx.files._qt_plugins)`)
=> Fixed out-of-sandbox library access path

openroad.bzl
=> make: Fix tcl error

BUILD, openroad.bzl
The user no longer has to guess which argument goes into which stage, but the list of this mapping is hardcoded into bazel-orfs.
If an argument is missing from STAGE_ARGS_USES, an error message is printed that includes:
if stage in STAGE_ARGS_USES[arg]}
Error: key "SDC_FILE" not found in dictionary
=> bazel-orfs: centralize mapping of variables onto stages

README.md, docker.bzl
This PR introduces option to use locally build images - if the sha256 is left empty, the `docker.bzl` checks if the given `image` is present locally and uses it.
=> Allow using locally built images

.github/scripts/build_local_target.sh, .github/scripts/extract_docker_revision.py, .github/workflows/ci.yml, BUILD, MODULE.bazel.lock, subpackage/BUILD, test/rtl/data_2048x8.sv, test/rtl/regfile_128x65.sv
This PR adds multiple tests, which come from Megaboom CI. To be more precise, moved are:
- `data_2048x8_generate_abstract` and `regfile_128x65_floorplan` targets. That includes their rules and source files.
- test subpackage `subpackage:tag_array_64x184_generate_abstract`
- `test-target-local-preinstalled-orfs` and `test-target-local-clean-setup` jobs, which test local flows. One is run in a docker container with openroad and yosys prebuilt, and the other one copies the binaries from a container. Both tests make use of a `build_local_target.sh` script, which runs and builds all steps of a given flow.
=> Migrate tests from megaboom to bazel-orfs

BUILD, README.md, make.tpl, mock_area.tcl, openroad.bzl
This PR reintroduces `mock_area` feature: creating additional mock area targets, which scale `CORE_AREA` and `DIE_AREA`, and use them to run floorplan and generate_abstract.
This PR also contains some minor README cleanup, like removing information about canonicalize targets.
=> Reintroduce `mock_area` feature

openroad.bzl
Fixes the use-case below, but adds a openroad dependency to synthesis stage, which we don't want.
```
$ bazel run //sram:top_fakeram_synth `pwd`/build
INFO: Invocation ID: e4503934-006a-48df-9122-93d487b05d85
INFO: Analyzed target //sram:top_fakeram_synth (0 packages loaded, 0 targets configured).
Target //sram:top_fakeram_synth up-to-date:
bazel-bin/sram/results/asap7/top/fakeram/1_synth.v
bazel-bin/sram/results/asap7/top/fakeram/1_synth.sdc
bazel-bin/sram/results/asap7/top/fakeram/mem.json
bazel-bin/sram/results/asap7/top/fakeram/1_synth.rtlil
INFO: Elapsed time: 0.050s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/sram/top_fakeram_synth.sh /home/oyvind/bazel-orfs/build …
```
=> synth: build/make gui_synth fix

sram/fakeram/sdq_17x64.lib
@jeffng-or @maliberty To view results:
```
bazel run //sram:top_fakeram_grt `pwd`/build
build/make gui_grt
```
in2reg 9.49+32.10=41.59ps
reg2out=633.21ps
633.21ps for a 17x64 SRAM at 7nm seems high...
```
>>> report_checks -from {addr_in[0]} -to {u_sdq_17x64/addr_in[0]}
Startpoint: addr_in[0] (input port)
Endpoint: u_sdq_17x64 (rising edge-triggered flip-flop clocked by clk)
Path Group: in2reg
Path Type: max
Delay    Time   Description
---------------------------------------------------------
0.00    0.00 ^ input external delay
0.00    0.00 ^ addr_in[0] (in)
9.49    9.49 ^ input1/Y (BUFx2_ASAP7_75t_R)
0.00    9.49 ^ u_sdq_17x64/addr_in[0] (sdq_17x64)
9.49   data arrival time
80.00   80.00   max_delay
0.00   80.00   clock reconvergence pessimism
-47.90   32.10   library setup time
32.10 …
```
=> sram: fix fakeram clock problem

sram/BUILD
@hovind Failing example of trying to mix and match .lib and .lef files:
```
$ bazel build //sram:top_mix_synth
INFO: Invocation ID: a5629799-b434-4c4b-b0c8-91ead8eec75f
INFO: Analyzed target //sram:top_mix_synth (0 packages loaded, 0 targets configured).
ERROR: /home/oyvind/bazel-orfs/sram/BUILD:69:10: Action sram/results/asap7/top/mix/1_synth.rtlil failed: missing input file '//sram:results/asap7/sdq_17x64/base/sdq_17x64.lef'
ERROR: /home/oyvind/bazel-orfs/sram/BUILD:69:10: Action sram/results/asap7/top/mix/1_synth.rtlil failed: 1 input file(s) do not exist
Target //sram:top_mix_synth failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/oyvind/bazel-orfs/sram/BUILD:69:10 Action sram/results/asap7/top/mix/1_synth.rtlil failed: 1 input file(s) …
```
=> sram: mix .lib and .lef files

sram/BUILD, sram/write_macros.tcl
@jeffng-or @maliberty This can be useful to run RTLMP_FLOW=1 SYNTH_HIERARCHICAL=1, then afterwards use this macro placement with flattened synthesis.
=> sram: take macro placement from one flow and use it another

.github/workflows/ci.yml, sram/BUILD, sram/write_floorplan.tcl
@hovind top_floorplan_deps targets can't be used for orfs_run() yet, so I used top_floorplan instead.
```
$ bazel build //sram:top_mix_floorplan
INFO: Invocation ID: d1f804db-8926-43a4-a737-4694b3d30be3
ERROR: /home/oyvind/bazel-orfs/sram/BUILD:87:9: in src attribute of orfs_run rule //sram:top_write_floorplan: '//sram:top_floorplan_deps' does not have mandatory providers: 'OrfsInfo'
ERROR: /home/oyvind/bazel-orfs/sram/BUILD:87:9: Analysis of target '//sram:top_write_floorplan' failed
ERROR: Analysis of target '//sram:top_mix_floorplan' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.065s, Critical Path: 0.00s
ERROR: Build did NOT complete successfully
```
I'd like to be able to run the this step with a locally hacked ORFS:
```
$ bazel run …
```
=> Sram mix floorplan

openroad.bzl
=> openroad.bzl: Support arguments to `orfs_run`

.github/scripts/build_local_target.sh, BUILD, MODULE.bazel, MODULE.bazel.lock, openroad.bzl
tag_array_64x184_generate_abstract now runs through all stages as there was some breakage in routing after ORFS reordered the 5_3_fillcell to be after detailed routing.
Reordering of ORFS stages is rare, can't recall last time.
=> orfs: bump

openroad.bzl
When running the mock_area flow with more than one SRAM, the same make file output declaration is used by multiple SRAMS:
```
ERROR: file 'make_mock_area_2_floorplan' is generated by these conflicting actions:
Label: //:sdq_17x64_floorplan_mock_area, //:ebtb_128x40_floorplan_mock_area
RuleClass: orfs_floorplan rule
```
Added the context name to the name of the output file to disambiguate it when the code is called for multiple SRAMs.
Caveat: this is not fully tested and I don't know the other usages of this file (e.g. there might be other hookups that also need to be updated to the new file name). It seems to get beyond the error that I was seeing and also seems to be running when I turn mock_area off.
megaboom test case: https://github.com/The-OpenROAD-Project/megaboom/pull/128
=> added context name to name of make file

BUILD, openroad.bzl, test/constraints-sram.sdc, test/rtl/lb_32x128_top.v
run through final when generating mock abstract to check that correct .lib and .lef files are used.
mock_area is broken.
mock_area should use the mock_area .lef from floorplan and the regular .lib file when generating an abstract.
Bug 1: there should be no cts, final, place, route, grt below.
```
$ bazel query //:* | grep lb_32x128 | grep mock
Loading: 0 packages loaded
//:lb_32x128_cts_mock_area
//:lb_32x128_cts_mock_area_deps
//:lb_32x128_final_mock_area
//:lb_32x128_final_mock_area_deps
//:lb_32x128_floorplan_mock_area
//:lb_32x128_floorplan_mock_area_deps
//:lb_32x128_grt_mock_area
//:lb_32x128_grt_mock_area_deps
//:lb_32x128_mock_area
//:lb_32x128_place_mock_area
//:lb_32x128_place_mock_area_deps
//:lb_32x128_route_mock_area
//:lb_32x128_route_mock_area_deps …
```
=> test: add lb_32x128_top to inspect mock abstract usage

openroad.bzl, sram/BUILD
```
$ bazel build //sram:sdq_17x64_floorplan_deps
INFO: Invocation ID: 9348e0e3-8b53-4151-a142-2c83b7e12d7d
INFO: Analyzed target //sram:sdq_17x64_floorplan_deps (0 packages loaded, 0 targets configured).
Target //sram:sdq_17x64_floorplan_deps up-to-date:
bazel-bin/sram/results/asap7/sdq_17x64/base/2_floorplan.short.mk
bazel-bin/sram/results/asap7/sdq_17x64/base/1_synth.rtlil
bazel-bin/sram/results/asap7/sdq_17x64/base/1_synth_unedited.v
bazel-bin/sram/results/asap7/sdq_17x64/base/1_synth.sdc
bazel-bin/sram/results/asap7/sdq_17x64/base/mem.json
bazel-bin/sram/results/asap7/sdq_17x64/base/1_synth.v
INFO: Elapsed time: 0.068s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
$ diff …
```
=> Stage outputs arguments used to support for instance naja

openroad.bzl
variant None defaults to 'base', so convert 'base' to None to avoid fixing iffy code.
Boarding up a broken window...
=> orfs_flow: canonicalize variant input

BUILD
@jeffng-or @maliberty @luarss FYI
For MegaBoom, the build times are ca. 12-24 hours, so "sweeps" of parameters will have to be planned manually. 
I'm wary of trying a million parameters with a credit card and an automatic cloud solution :-)
Bazel "property sweep at home"... "at home" here as in a mom telling the kids that "We have burgers at home" when passing by a burger resturant... Of course the "burgers at home" are not nearly as nice as that fancy burger resturant... But, it gets the job done. :-)
These tests are run in parallel:
- runs all the tests in parallel
- artifacts are produced so they can be downloaded and inspected if the build happens on a server
In this simply example, I'm only after a go/no go, but for other properties it might be interesting to run some scripts to …
=> example: density sweep

sram/BUILD
=> mock-naja: add .lib file from a macro

openroad.bzl
Hack to make `$(location <label>)` expansions
work when configuration files are generated for
executables that are run with `bazelisk run`.
Hacks a `File`'s `.path` into a `.short_path`.
@oharboe
=> openroad.bzl: Hack away prefix

BUILD, test/rtl/regfile_128x65.sv
The intention here is to document the gate netlist file group use-case.
It needs work... fails:
```
$ bazel build lb_32x128_final
INFO: Analyzed target //:lb_32x128_final (1 packages loaded, 1652 targets configured).
Target //:lb_32x128_final up-to-date:
bazel-bin/results/asap7/lb_32x128/base/6_final.gds
bazel-bin/results/asap7/lb_32x128/base/6_final.odb
bazel-bin/results/asap7/lb_32x128/base/6_final.sdc
bazel-bin/results/asap7/lb_32x128/base/6_final.spef
bazel-bin/results/asap7/lb_32x128/base/6_final.v
bazel-bin/reports/asap7/lb_32x128/base/6_finish.rpt
bazel-bin/reports/asap7/lb_32x128/base/VDD.rpt
bazel-bin/reports/asap7/lb_32x128/base/VSS.rpt
INFO: Elapsed time: 0.374s, Critical Path: 0.02s
INFO: Build completed successfully, 1 …
```
=> netlist: gate netlist filegroup use-case

BUILD, sweep.bzl, wns_report.py
and check for valid keys in the sweep dictionary to avoid silent errors
=> orfs_sweep: rename variables to arguments for consistency

BUILD, fastroute.tcl, openroad.bzl
Fixes:
```
$ rm -rf /tmp/foo && bazel run lb_32x128_sky130hd_grt /tmp/foo gui_grt [ERROR STA-0340] cannot open './fastroute.tcl'.
[ERROR GUI-0070] Error: open.tcl, 74 STA-0340
```
=> open: fixes e.g. FASTROUTE_TCL error in open.tcl

BUILD, alu.v, yosys.bzl
```
$ bazel build alu
INFO: Invocation ID: 8abc9dce-1f7a-4ffc-89fc-1405ce367437
INFO: Analyzed target //:alu (0 packages loaded, 0 targets configured).
ERROR: /home/oyvind/bazel-orfs/BUILD:460:8: Executing genrule //:alu failed: (Exit 127): bash failed: error executing Genrule command (from target //:alu) /bin/bash -c ... (remaining 1 argument skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
+ ldd external/_main~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys
+ external/_main~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys -p 'read_verilog ./alu.v; write_json bazel-out/k8-fastbuild/bin/alu.json'
/bin/bash: line 4: …
```
=> yosys: show standalone use-case

openroad.bzl, sweep.bzl
Check for targets that should have, but don't, have the tags = ["manual"] set:
bazel query 'kind(rule, ...) - attr(tags, manual, ...)'
=> bazel: forward more kwargs

openroad.bzl
=> LoggingInfo: typo, drcs and jsons were mixed up with reports

MODULE.bazel, MODULE.bazel.lock, docker.BUILD.bazel
Before this fix:
```
$ bazel run tag_array_64x184_synth_deps /tmp/xxx do-yosys
INFO: Invocation ID: b7a692b2-3fa4-46b2-bc4b-7ea82cd6e1da
INFO: Analyzed target //:tag_array_64x184_synth_deps (1 packages loaded, 1644 targets configured).
Target //:tag_array_64x184_synth_deps up-to-date:
bazel-bin/results/asap7/tag_array_64x184/base/1_synth.short.mk
INFO: Elapsed time: 36.496s, Critical Path: 0.08s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Running command line: bazel-bin/results/asap7/tag_array_64x184/base/tag_array_64x184_synth_deps.sh /tmp/xxx do-yosys
external/_main~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/flow/scripts/synth.sh external/_main~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/flow/scripts/sy …
```
=> Fix yosys deps

openroad.bzl
ADDITIONAL_LEFS did not have the paths fixed as only the first path in the array was fixed
=> deps: fix foo_deps target for list variables

BUILD
we do a full run elsewhere in the flow:
$ bazelisk query :* | grep final
Loading: 0 packages loaded
//:lb_32x128_final
//:lb_32x128_final_deps
//:lb_32x128_ihp-sg13g2_final
//:lb_32x128_ihp-sg13g2_final_deps
//:lb_32x128_sky130hd_final
//:lb_32x128_sky130hd_final_deps
//:regfile_128x65_final
//:regfile_128x65_final_deps
=> test: reduce running times
