The-OpenROAD-Project/bazel-orfs

- BUILD
- openroad.bzl
This PR does a little bit of cleanup in bazel files with [buildifier](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md) tool.
CC @oharboe
> Bazel files: Improve formatting with buildifier

- .github/workflows/ci.yml
- BUILD
- MODULE.bazel
- test/constraints-top.sdc
> tests: avoid future problems in global routing when ORFS is upgraded

- BUILD
- README.md
- openroad.bzl
- subpackage/BUILD
> abstract: mock_abstract is superfluous, enough to specify abstract_stage

- docker_shell.sh
Error `xauth: unable to generate an authority file name` is caused by not specified Xauthority file location, usually read from `XAUTORITY` variable. But bazel-orfs uses `--incompatible_strict_action_env` option, which makes the variable not available during `bazel build ...`.
Passing `XAUTORITY` with `--aciton_env` will invalidate the shared cache (as probably each user has different value set), therefore this PR moves X authorities management to _interactive_ section (which is run only when `--interactive` is used, basically when user run scripts manually), as it is only required for GUI. Moreover, error management was improved.
> Fix `xauth: unable to generate an authority file name`

- openroad.bzl
This PR adds missing dependencies for GUI targets.
> openroad: Add missing dependencies for GUI targets

- openroad.bzl
This PR creates custom `CPUHeavyGenrule`, which requires whole CPU and uses it to prevent running multiple route stages at once.
> Do not run route stages in parallel

- LICENSE
Adding the same license file as in [The-OpenROAD-Project/megaboom](https://github.com/The-OpenROAD-Project/megaboom) to this project.
> LICENSE: Add BSD 3-Clause license

- openroad.bzl
This PR adds filtering of targets' inputs to not depend on log and report files.
> Remove logs and report files from targets' inputs

- openroad.bzl
The old approach doesn't work for generated verilog files. @eszpotanski does this seem reasonable?
> openroad: Support generated verilog

- docker.BUILD.bazel
Fixes make issue snags w.r.t. *.sh files in https://github.com/The-OpenROAD-Project/bazel-orfs/issues/100
> docker: Extract flow/util/*.sh files

- openroad.bzl
> synth: fix 'make memory'

- openroad.bzl
@jeffng-or FYI
```
$ bazel run tag_array_64x184_generate_abstract_deps `pwd`/build
$ build/make do-generate_abstract
mkdir -p .//logs/asap7/tag_array_64x184/base .//reports/asap7/tag_array_64x184/base
(/usr/bin/time -f 'Elapsed time: %E[h:]min:sec. CPU time: user %U sys %S (%P). Peak memory: %MKB.' external/_main~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad -exit -no_init -threads 16  external/_main~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/flow/scripts/generate_abstract.tcl -metrics .//logs/asap7/tag_array_64x184/base/generate_abstract.json) 2>&1 | tee .//logs/asap7/tag_array_64x184/base/generate_abstract.log
OpenROAD HEAD-HASH-NOTFOUND 
Features included (+) or not (-): +Charts +GPU +GUI +Python
This program is licensed under the …
```
> Generate abstract deps

- MODULE.bazel.lock
- docker.bzl
it is enough to create a stopped container
> docker: no need to run image to copy files from it

- .github/workflows/ci.yml
- BUILD
- README.md
- make.tpl
- openroad.bzl
This PR adds `variant` option to `orfs_flow`, which is the equivalent of `FLOW_VARIANT` from ORFS.
> Implement `variant` argument

- BUILD
- README.md
- make.tpl
- openroad.bzl
- subpackage/BUILD
@oharboe FYI.
@mleonowicz what do you think about https://github.com/The-OpenROAD-Project/bazel-orfs/commit/c9861eb4fee927d2f8029734999ae3c1fdaaffc2 instead of adding multiple sources?
> openroad: Combine canonicalization and synth actions into one step

- make.tpl
> make.tpl: Remove absolute paths

- openroad.bzl
> openroad: Add forwarded files to runfiles

- BUILD
- test/constraints-sram.sdc
> Ci tests tweaks

- .bazelrc
- .gitignore
- cred_helper.py
> Bazel user rc

- openroad.bzl
> openroad: Fix mock area bug

- sram/fakeram/top.v
> sram: fix address width

- MODULE.bazel
- MODULE.bazel.lock
- openroad.bzl
> Make run support

- openroad.bzl
- sram/BUILD
- sram/write_floorplan.tcl
> Dependencies configuration

- openroad.bzl
- sram/BUILD
- sram/write_macros.tcl
@hovind the user adds "source $::env(SCRIPTS_DIR)/gui.tcl" if they want to run this script first.
> BUILD: orfs_run runs any script

- docker.BUILD.bazel
> docker: Export more files

- README.md
- deploy.tpl
- openroad.bzl
> Local hacking

- MODULE.bazel
- MODULE.bazel.lock
- openroad.bzl
> Orfs bump no more macros variable

- openroad.bzl
> openroad.bzl: Add `orfs_macro` rule

- sram/BUILD
> naja: example of how to create a base and naja variant

- openroad.bzl
variables in all stages were not listed as sources in all stages.
> sources: fix gaffe in which variables are at which stage

- openroad.bzl
> synth: .sdc file is generated as part of synth

- .github/scripts/smoketests.sh
- deploy.tpl
- openroad.bzl
> openroad.bzl: Rename deps

- .github/scripts/smoketests.sh
- BUILD
- sweep-wns.tcl
- sweep.bzl
- wns_report.py
- wns_report_test.py
- write_binary.bzl
make sweep in megaboom reusable
> sweep: add sweep macro

- .github/scripts/build_local_target.sh
- MODULE.bazel
- MODULE.bazel.lock
- README.md
- openroad.bzl
do-yosys-stats is no more, hierarchical synthesis is now done in a single stage.
> orfs: bump

- openroad.bzl
allows adding extra files, like .mem files used in synthesis to initialize sram
> orfs_flow: add stage_data

- deploy.tpl
> orfs_flow: remove spammy harmless syntax error message

- BUILD
- MODULE.bazel
- MODULE.bazel.lock
- README.md
- openroad.bzl
- sram/BUILD
- subpackage/BUILD
@maliberty @eder-matheus FYI https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2959
> orfs: bump, 2_2_floorplan_io removed

- .bazelrc
- docker.BUILD.bazel
better w.r.t. bazel 8 that is stricter about this.
> bazel: no empty glob()s

- openroad.bzl
> Logs transitive cleanup

- BUILD
- another/tag_array_64x184.sv
- test/mock/tag_array_64x184.sv
Modify initial conditions very slightly so that we don't run into https://github.com/The-OpenROAD-Project/OpenROAD/issues/7745
> tests: workaround for placement snag

- check_mock_area.tcl
Modify initial conditions very slightly so that we don't run into https://github.com/The-OpenROAD-Project/OpenROAD/issues/7745
revert this commit when OpenROAD is fixed.
> tests: workaround for placement snag, part 2

- MODULE.bazel.lock
- extension.bzl
- orfs-patch.txt
Nice when waiting for a PR to land
> orfs: added patching capability to docker image

- tools/pin/pin.py
Tested in the ascenium repository.
> pin: fix pinning

- sram/BUILD
merged.lib is gone https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/3419
> naja: disable for now, wean it of merged.lib
